# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "AI-powered pre-push code review hook"
  homepage "https://github.com/GyeongHoKim/preflight"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.2.0/preflight_0.2.0_darwin_amd64.tar.gz"
      sha256 "6e15590b43d25005f0b4eb2fb3cb2ba42cde593fda8aef6b751df1fbd2d4759f"

      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.2.0/preflight_0.2.0_darwin_arm64.tar.gz"
      sha256 "d013767a836582a75de3971cee414d781b9c21a2def35d743045c4fb4c47e67a"

      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.2.0/preflight_0.2.0_linux_amd64.tar.gz"
      sha256 "7ed6e2133738cfc8a9c554d396a23ec34b88d7c3f808e628556d56b6626a40bc"
      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.2.0/preflight_0.2.0_linux_arm64.tar.gz"
      sha256 "82c6cf4229aa9914d3df9431e610cefc61cd3668d89aadf1f8cded4d3b310537"
      define_method(:install) do
        bin.install "preflight"
      end
    end
  end
end
