# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "AI-powered pre-push code review hook"
  homepage "https://github.com/GyeongHoKim/preflight"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.4.1/preflight_0.4.1_darwin_amd64.tar.gz"
      sha256 "ee1f3ec7135282ba567c9481f6187ed7fdc3eb72276f7f99937e6b5417c3a271"

      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.4.1/preflight_0.4.1_darwin_arm64.tar.gz"
      sha256 "97cc08cf4e6361b29790258af8fcaacf85bc2aacd39a702e7c00bea183ec49ad"

      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.4.1/preflight_0.4.1_linux_amd64.tar.gz"
      sha256 "aa2ad15510188253e6d2bcc25251a6e06199344ec792e4658b1aa74fef148f3d"
      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GyeongHoKim/preflight/releases/download/v0.4.1/preflight_0.4.1_linux_arm64.tar.gz"
      sha256 "0c92e792b72e454414e0a60062d9db82030f33fd8539268307268cc57b216d8b"
      define_method(:install) do
        bin.install "preflight"
      end
    end
  end
end
