# This file was generated by GoReleaser. DO NOT EDIT.
cask "naeryeo" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "9525b5115319687e2ce67c5cddd67f1d8c81cb56df3a271755c8c66addf4a26f"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4106aa4a0660d3ba9d579c10cb8d20d717a8ca77f341a326fa799c4248f005a2"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac369d0cb35c8a577aa9baa2f49307ead777ab07ad10e7a9971d56b0f8600dc2"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cecd623b20f8ae0382291fb2381ad8444f5e9d2841a86f1b67a5e17cd556c6e0"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "naeryeo"
  desc "CLI + MCP stdio server for Korean public-transit routing"
  homepage "https://github.com/GyeongHoKim/naeryeo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "naeryeo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/naeryeo"]
    end
  end

  # No zap stanza required
end
