# This file was generated by GoReleaser. DO NOT EDIT.
cask "naeryeo" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c9d0c4b7ff1c7021a668a57255c4a43ee428fe534a66c125112ab02f0986bd4a"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e86a48cb809f39725947e27321db5189f76d600db4b2be420a740c217f8d3367"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01ed93bc5574b3a7637966cfad9955253133408b0914654712319a92b9318731"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6d41c7f4fef147c77465527701bb6e61a239a128df8e548ae3c7d76d22dbe3d"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "naeryeo"
  desc "CLI + MCP stdio server for Korean public-transit routing"
  homepage "https://github.com/GyeongHoKim/naeryeo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "naeryeo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/naeryeo"]
    end
  end

  # No zap stanza required

end
