# This file was generated by GoReleaser. DO NOT EDIT.
cask "naeryeo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ae9c910c97d3d944f2cb46f815e1ae9f24585f8c534cf75e232978428d6755fa"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c8ca2daf90add32920da8ed164a7135cd4493463f1e4bb2bcecad01862d91a9"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "789e674ca53c8f899ba27d991a4a81fe73c4e5a77aac09d589e3d0a925aa922f"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d109a1f6f52dbad845658dd5ac3d64fecd255a9f76489255863eb71abff1cef"
      url "https://github.com/GyeongHoKim/naeryeo/releases/download/v#{version}/naeryeo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "naeryeo"
  desc "CLI + MCP stdio server for Korean public-transit routing"
  homepage "https://github.com/GyeongHoKim/naeryeo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "naeryeo"

  # No zap stanza required

end
