# This file was generated by GoReleaser. DO NOT EDIT.
cask "pokemon-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0ce14a7ad1f6a5ae58a7099de9f94af35c42ed84997089841935b28b66337e1e"
      url "https://github.com/GyeongHoKim/pokemon-cli/releases/download/v#{version}/pokemon-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "449fb8761254f6c27e5e1a759b1a33e9087cd148fbc27d7548acee47cf7c3441"
      url "https://github.com/GyeongHoKim/pokemon-cli/releases/download/v#{version}/pokemon-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62408e861c891ace2b649e5029787304f7ec55897d44e6a5439670ed8897bb5a"
      url "https://github.com/GyeongHoKim/pokemon-cli/releases/download/v#{version}/pokemon-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3813974b1d54fc532bdadb86750d970e20c68020e431c0e29c73346c8757c4ac"
      url "https://github.com/GyeongHoKim/pokemon-cli/releases/download/v#{version}/pokemon-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pokemon-cli"
  desc "Pikachu running around your terminal"
  homepage "https://github.com/GyeongHoKim/pokemon-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pokemon-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pokemon-cli"]
    end
  end

  # No zap stanza required

end
